# Generated by Django 4.2.7 on 2024-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, upload_to='board/files/%Y/%m/%d/'),
        ),
    ]
